#mybatis
mybatis:
  type-aliases-package: com.jureumuing.nolhac.entity #entity ??
  mapper-locations: mapper/**/*.xml

spring:
  application:
    name: nolhac
    profiles:
      active: dev

  #postgreSQL
  datasource:
    url: jdbc:postgresql://welcome5-db.c7zdxujz2wc8.ap-northeast-2.rds.amazonaws.com:5432/nollhac #??DB?(rds??? localhost?? ?????? ????), ardiary_nf: no foreign ??? ?? ??? ??????. ??? ?? ????? _nf??? ?
    driver-class-name: org.postgresql.Driver
    username: admin5
    password: jongsul5

server:
  port: 8019
  forward-headers-strategy: framework
  
jwt:
  secretKey: jureumuingNolHakKeyJwtSecret12411128094456375876587

